### ISSUE TITLE
Where is the "_netG_att"?

### ISSUE THREAD

**Issue by FouriYe** [EthanZhu90/ZSL_GAN_CVPR18#1]
In train_GBU.py, line 18 is "from models import _netD, _netG_att, _param". However, I can't find "_netG_att" in models. So, where is the "_netG_att"?

**Comment by Monica-hr** [comment]
Hello, have you solved this problem? I have the same problem and hope to get a reply，thank you.

**Comment by FouriYe** [comment]
@Monica-hr the author has supplied the "_netG_att"  in models.py
