### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by liubl1217** [EthanZhu90/ZSL_GAN_CVPR18#2]
Hi, I just notice u update the results on GBU setting. H of CUB dataset is now 41.78, but I can only achieve 32.71. Is there any modification to the code?

**Comment by fshamshirdar** [comment]
Any thoughts on this? Same for me, does not go higher than 32. Based on what setup did you get 41.78?

**Comment by fshamshirdar** [comment]
Other papers also reported 34.3! This is just not right!!

**Comment by Programmergg** [comment]
> Other papers also reported 34.3! This is just not right!!
Hello,why my result on CUB is so low,can you 

> Other papers also reported 34.3! This is just not right!!

Hello, why is my result so low in Cub? Can you share your parameters? Thank you very much!
